"""empty message

Revision ID: 266ba052619b
Revises: 7f777ee0e06b
Create Date: 2024-08-25 04:36:34.006849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266ba052619b'
down_revision = '7f777ee0e06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
